name = "multiroom-playground"
main = "src/main.js"
compatibility_date = "2025-01-06"

[durable_objects]
bindings = [
  { name = "LOBBY", class_name = "LobbyDO" },
  { name = "ROOM",  class_name = "RoomDO"  },
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["LobbyDO", "RoomDO"]
