name = "multiroom-playground"
main = "src/index.js"
compatibility_date = "2025-01-06"
compatibility_flags = ["nodejs_compat"]

[[durable_objects.bindings]]
name = "LOBBY"
class_name = "LobbyDO"

[[durable_objects.bindings]]
name = "ROOM"
class_name = "RoomDO"

[[migrations]]
tag = "v1"
new_classes = ["LobbyDO", "RoomDO"]
