name = "multiroom-ws"
main = "src/index.js"
compatibility_date = "2026-01-06"

[durable_objects]
bindings = [
  { name = "LOBBY", class_name = "LobbyDO" },
  { name = "ROOM", class_name = "RoomDO" }
]

[[migrations]]
tag = "v1"
new_classes = ["LobbyDO", "RoomDO"]
